# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aleks Gorbenko | Web Developer
email: AleksEdGorbenko@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a web developer based in London, UK.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: algorben
github_username:  aleksgorbenko

# Build settings
markdown: kramdown
exclude: ['node_modules',
          'gulpfile.js',
          'Gemfile',
          'Gemfile.lock',
          'package.json']

sass:
  # loading path from site root
  # default to _sass

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  # see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  # on a typical twitter bootstrap stats are :
  # nested 138,7kB, compact 129,1kB, expanded 135,9 kB, compressed 122,4 kB
  style: compressed
